# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47bcb7e7f3dbaac3692c975a613cd94a910961e26fd504edbcd8267f5bcd765f3e207309c93a3811c2cd5af4a4e44ee9d0cadf5186f9199d8e74228240a5b268

test:
  secret_key_base: 17e85c6630aef07d0ed61de70c8d1a1293731412f32f477d7937a5cfdb3d4f7cea14ed97071af36a8241986bd6c3860688c57bf4b4a9e220f368b78de8819e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
